### ISSUE TITLE
is it support compile Linux kernel 

### ISSUE THREAD

**Issue by ayoubelmhamdi** [void-linux/void-docker#1]
sometimes, I want to compile a Linux kernel like Gentoo, but must install multi-app and dependencies..  
- is there a way to use build an image docker to run `make menuconfig` very easy?

**Comment by Vaelatern** [comment]
It's a general tool.

Anything you can do in a dockerfile, you can do in a dockerfile.

Anything you can do in a container, you can do in a container.

So can you build a container that's well suited to compiling a kernel? My answer would have to be "Yes."

That is probably outside the scope of this repo or even this project, since we don't have that need.
